### ISSUE TITLE
你好，我在运行eval文件后，得到的结果全都是0，这种情况可能是什么原因引起的呢，训练时感觉还是正常的

### ISSUE THREAD

**Issue by lalalalala7** [Kamino666/S2VT-video-caption#1]
computing Bleu score...
{'testlen': 0, 'reflen': 0, 'guess': [0, 0, 0, 0], 'correct': [0, 0, 0, 0]}
ratio:0.000001
Bleu_1: 0.000
Bleu_2: 0.000
Bleu_3: 0.000
Bleu_4: 0.000
computing Rouge score...
ROUGE_L: 1.000
***********************

**Comment by lalalalala7** [comment]
@Kamino666

**Comment by Kamino666** [comment]
可以检查一下模型的输出内容，也就是prediction_dict 这个变量

**Comment by lalalalala7** [comment]
检查过这个变量是没问题的，问题应该是出现在
print('tokenization...')
        tokenizer = PTBTokenizer()
        gts = tokenizer.tokenize(gts)
        res = tokenizer.tokenize(res)
        print(gts)
        print(res)
这个过程中 ，这里的输出是
{'-8y1Q0rA3n8_108_115': ['']}
{'-8y1Q0rA3n8_108_115': ['']}
应该不是正确的输出把  但还是没找到出现这个错误的原因是什么

**Comment by Kamino666** [comment]
这部分是[这个库](https://github.com/tylin/coco-caption)里的代码了，可以看看java的环境是否正常，那个库里的java封装应该不会有大问题。

**Comment by lalalalala7** [comment]
谢谢啦，我没有配置java环境，在网上也没有查到这个要配置什么样的Java环境，你可以告诉我一下吗 ？我刚刚开始做这个课题，这也是我运行的第一个代码，所以不是很懂，非常感谢

**Comment by lalalalala7** [comment]
是我没有配置Java环境的问题，现在已经解决了，谢谢你的代码和解答！

**Comment by Kamino666** [comment]
😄 谢谢你的关注，有什么问题可以发邮箱或者提issue
